import React from 'react'
import Head from 'next/head'
import CheckoutProduct from '../Components/Products/CheckoutProduct'

const checkout = () => {
  return (
    <>
      <Head>
        <title>Amazon Challenge - Checkout</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="checkout">
        <div className="checkout__left">
          <h1>Shoppig Cart</h1>
          <div className="checkout__products">
            <CheckoutProduct/>
          </div>
        </div>
        <div className="checkout__right">

        </div>
      </div>
    </>
  )
}

export default checkout