import Head from 'next/head'
import flash1 from '../Assets/home-flash/1.jpg'
import flash2 from '../Assets/home-flash/2.jpg'
import flash3 from '../Assets/home-flash/3.jpg'
import flash4 from '../Assets/home-flash/4.jpg'
import flash5 from '../Assets/home-flash/5.jpg'
import flash6 from '../Assets/home-flash/5.jpg'
import flash7 from '../Assets/home-flash/7.jpg'
import flash8 from '../Assets/home-flash/8.jpg'
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation } from 'swiper';
import 'swiper/css';
import 'swiper/css/navigation';
import HomeProducts from '../Components/Products/HomeProducts/HomeProduct1'

const HomeFlash = (props) => {
    const { imgUrl } = props;
    return (
        <div className="home__flash__single">
            <img src={imgUrl.src} alt="" width='100%' />
        </div>
    )
}

export default function Home() {
    return (
        <>
            <Head>
                <title>Amazon Challenge - Home</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='home'>
                <div className="home__flash">
                    <Swiper
                        modules={[Navigation]}
                        spaceBetween={0}
                        slidesPerView={1}
                        navigation
                    >
                        <SwiperSlide>
                            <HomeFlash imgUrl={flash1} />
                        </SwiperSlide>
                        <SwiperSlide>
                            <HomeFlash imgUrl={flash2} />
                        </SwiperSlide>
                        <SwiperSlide>
                            <HomeFlash imgUrl={flash3} />
                        </SwiperSlide>
                        <SwiperSlide>
                            <HomeFlash imgUrl={flash4} />
                        </SwiperSlide>
                        <SwiperSlide>
                            <HomeFlash imgUrl={flash5} />
                        </SwiperSlide>
                        <SwiperSlide>
                            <HomeFlash imgUrl={flash6} />
                        </SwiperSlide>
                        <SwiperSlide>
                            <HomeFlash imgUrl={flash7} />
                        </SwiperSlide>
                        <SwiperSlide>
                            <HomeFlash imgUrl={flash8} />
                        </SwiperSlide>
                    </Swiper>
                </div>
                <HomeProducts />
            </main>
        </>
    )
}
